kind: Namespace
apiVersion: v1

metadata:
  name: nginx-ns

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  namespace: nginx-ns
  labels:
    app: nginx-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app

  template:
    metadata:
      name: nginx-pod
      namespace: nginx-ns
      labels:
        app: nginx-app

    spec:
      containers:
      - name: nginx-con
        image: nginx:latest
        ports: 
        - containerPort: 80

---

apiVersion: v1
kind: Service

metadata:
  name: nginx-svc
  namespace: nginx-ns

spec:
  selector:
    app: nginx-app
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: nginx-ing
  namespace: nginx-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
  - host: app1.localhost
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nginx-svc
            port:
              number: 80