kind: Namespace
apiVersion: v1

metadata:
  name: mysql-ns

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: mysql-ns
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# spec:
#   volumeName: mysql-pv
#   volumeMode: Filesystem
#   storageClassName: standard
#   selector:
#     matchLabels:
#       release: "stable"
#     matchExpressions:
#       - {key: environment, operator: In, values: [dev]}

---

kind: Secret
apiVersion: v1

metadata:
  name: mysql-secret
  namespace: mysql-ns

type: opaque

data:
  MYSQL_ROOT_PASSWORD: QWRtaW4xMjM=

# spec:
#   volumes:
#     - name: secret-volume
#       secret:
#         secretName: dotfile-secret
#   containers:
#     - name: dotfile-test-container
#       image: registry.k8s.io/busybox
#       command:
#         - ls
#         - "-l"
#         - "/etc/secret-volume"
#       volumeMounts:
#         - name: secret-volume
#           readOnly: true
#           mountPath: "/etc/secret-volume"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: mysql-ns

data:
  MYSQL_DATABASE: db-one

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql-deployment
  namespace: mysql-ns
  labels:
    app: mysql-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql-app

  template:
    metadata:
      name: mysql-pod
      namespace: mysql-ns
      labels:
        app: mysql-app

    spec:
      containers:
      - name: mysql-con
        image: mysql:latest
        ports: 
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-data
        env:
        - name : MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name : MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
      resources:
        requests:
          # 100/1000 of a core = 10%
          cpu: 100m
          # minimum memory to run the pods
          memory: 256Mi

        limits:
          cpu: 200m
          memory: 512Mi
              
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mysql-hpa
  namespace: mysql-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mysql-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50


# apiVersion: v1
# kind: Service

# metadata:
#   name: mysql-svc
#   namespace: mysql-ns

# spec:
#   selector:
#     app: mysql-app
#   ports: 
#     - protocol: TCP
#       port: 3306
#       targetPort: 3306

# ---

# apiVersion: networking.k8s.io/v1
# kind: Ingress

# metadata:
#   name: mysql-ing
#   namespace: mysql-ns
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /

# spec:
#   rules:
#   - host: app3.localhost
#     http:
#       paths:
#       - pathType: Prefix
#         path: /
#         backend:
#           service:
#             name: mysql-svc
#             port:
#               number: 3306