apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  # this must not be namespaced
  # as it will be deleted if, resources under namespace are deleted
  # namespace: mysql-ns
spec:
  storageClassName: standard

  capacity:
    storage: 5Gi

  accessModes:
  - ReadWriteOnce

  hostPath:
    path: "/mnt/data"
    
  # claimRef:
  #   name: mysql-pvc
  #   namespace: mysql-ns

---